name: fresh_voice_app
description: A fresh Flutter project with Firebase phone auth, Agora voice rooms, multi-room support, and gift system.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^3.15.0
  firebase_auth: any
  cloud_firestore: any
  agora_uikit: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
